# Generated by Django 6.0.2 on 2026-04-05 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0006_agente_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_archivo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de archivo')),
                ('adjunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_virtual', to='notas.adjunto', verbose_name='Adjunto')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_virtual', to='notas.agente', verbose_name='Agente')),
                ('archivado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_archivados', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_virtual', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Documento de Legajo (virtual)',
                'verbose_name_plural': 'Documentos de Legajo (virtual)',
                'ordering': ['-fecha_archivo'],
            },
        ),
    ]
