# Generated by Django 6.0.2 on 2026-04-06 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_archivo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de archivo')),
            ],
            options={
                'verbose_name': 'Documento de Legajo (virtual)',
                'verbose_name_plural': 'Documentos de Legajo (virtual)',
                'ordering': ['-fecha_archivo'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('legajo', models.CharField(help_text='Número de legajo (usado para iniciar sesión)', max_length=20, unique=True, verbose_name='Legajo')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('dni', models.CharField(blank=True, help_text='Documento Nacional de Identidad', max_length=15, null=True, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('situacion_revista', models.CharField(blank=True, choices=[('PLANTA', 'Planta permanente'), ('CONTRATADO', 'Contratado'), ('PASANTE', 'Pasante'), ('OTRO', 'Otro')], max_length=30, null=True, verbose_name='Situación de revista')),
                ('activo_rrhh', models.BooleanField(default=True, help_text='Vigencia en nómina / legajo; independiente del acceso al sistema (is_active).', verbose_name='Activo (RRHH)')),
                ('rol', models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('CONSULTOR', 'Consultor')], help_text='Sin rol = sin permisos de aplicación (solo ficha institucional).', max_length=20, null=True, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['apellido', 'nombres'],
            },
        ),
    ]
