# Generated by Django 6.0.2 on 2026-04-06 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes', to='notas.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='agente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='documentolegajo',
            name='adjunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_virtual', to='notas.adjunto', verbose_name='Adjunto'),
        ),
        migrations.AddField(
            model_name='documentolegajo',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_virtual', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='documentolegajo',
            name='archivado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_archivados', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='documentolegajo',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_legajo_virtual', to='notas.nota', verbose_name='Nota'),
        ),
    ]
