# Generated by Django 6.0.2 on 2026-04-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0003_rename_nombre_to_nombres_if_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si True, el sistema obliga al agente a cambiar su contraseña en el próximo login.', verbose_name='Debe cambiar contraseña'),
        ),
    ]
