# Generated by Django 6.0.2 on 2026-04-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0004_agente_debe_cambiar_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario del sistema',
                'verbose_name_plural': 'Usuarios del sistema',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('agentes.agente',),
        ),
        migrations.AlterModelOptions(
            name='agente',
            options={'ordering': ['apellido', 'nombres'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes / Personal'},
        ),
    ]
