# Generated by Django 6.0.2 on 2026-04-06 04:02

from django.db import migrations, models
from django.db.models import F


def forwards_rellenar_flags(apps, schema_editor):
    Agente = apps.get_model("agentes", "Agente")
    Agente.objects.update(agente_activo=F("activo_rrhh"))
    Agente.objects.filter(is_active=True).exclude(rol__isnull=True).exclude(
        rol=""
    ).update(usuario_sistema=True)


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0005_usuariosistema_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='agente_activo',
            field=models.BooleanField(default=True, help_text='Indica que el agente es personal activo de la institución.', verbose_name='Agente activo'),
        ),
        migrations.AddField(
            model_name='agente',
            name='usuario_sistema',
            field=models.BooleanField(default=False, help_text='Indica que el agente tiene acceso al sistema de gestión. Se activa exclusivamente desde el sistema, nunca desde el admin.', verbose_name='Usuario del sistema'),
        ),
        migrations.RunPython(forwards_rellenar_flags, migrations.RunPython.noop),
    ]
