# Generated by Django 6.0.2 on 2026-04-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0006_agente_activo_usuario_sistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioSistema',
        ),
        migrations.AlterModelOptions(
            name='agente',
            options={'ordering': ['apellido', 'nombres'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='documentolegajo',
            options={'ordering': ['-fecha_archivo'], 'verbose_name': 'Documento de legajo', 'verbose_name_plural': 'Documentos de legajo'},
        ),
    ]
