# Generated by Django 6.0.2 on 2026-02-19 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(help_text='Formato: NOTA-YYYY-NNNN (generado automáticamente)', max_length=20, unique=True, verbose_name='Número de Nota')),
                ('fecha_ingreso', models.DateField(help_text='Fecha en que la nota ingresó al sistema', verbose_name='Fecha de Ingreso')),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite para resolver la nota', null=True, verbose_name='Fecha Límite')),
                ('remitente', models.CharField(help_text='Persona o entidad que envía la nota', max_length=200, verbose_name='Remitente')),
                ('area_origen', models.CharField(help_text='Área o departamento de origen de la nota', max_length=100, verbose_name='Área de Origen')),
                ('tema', models.CharField(help_text='Tema o asunto principal de la nota', max_length=200, verbose_name='Tema')),
                ('descripcion', models.TextField(help_text='Descripción detallada del contenido de la nota', verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('INGRESADA', 'Ingresada'), ('EN_REVISION', 'En Revisión'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('EN_ESPERA', 'En Espera'), ('DEVUELTA', 'Devuelta'), ('RESUELTA', 'Resuelta'), ('ARCHIVADA', 'Archivada'), ('ANULADA', 'Anulada')], default='INGRESADA', max_length=20, verbose_name='Estado')),
                ('canal_ingreso', models.CharField(choices=[('EMAIL', 'Email'), ('PRESENCIAL', 'Presencial'), ('TELEFONO', 'Teléfono'), ('SISTEMA', 'Sistema'), ('OTRO', 'Otro')], default='PRESENCIAL', max_length=20, verbose_name='Canal de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('anulada', models.BooleanField(default=False, help_text='Indica si la nota ha sido anulada', verbose_name='Anulada')),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Motivo por el cual la nota fue anulada', null=True, verbose_name='Motivo de Anulación')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó la nota en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario responsable de procesar la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el evento', verbose_name='Fecha y Hora')),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('ACTUALIZACION', 'Actualización'), ('ANULACION', 'Anulación'), ('ARCHIVADO', 'Archivado')], max_length=20, verbose_name='Tipo de Evento')),
                ('estado_anterior', models.CharField(blank=True, choices=[('INGRESADA', 'Ingresada'), ('EN_REVISION', 'En Revisión'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('EN_ESPERA', 'En Espera'), ('DEVUELTA', 'Devuelta'), ('RESUELTA', 'Resuelta'), ('ARCHIVADA', 'Archivada'), ('ANULADA', 'Anulada')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, choices=[('INGRESADA', 'Ingresada'), ('EN_REVISION', 'En Revisión'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('EN_ESPERA', 'En Espera'), ('DEVUELTA', 'Devuelta'), ('RESUELTA', 'Resuelta'), ('ARCHIVADA', 'Archivada'), ('ANULADA', 'Anulada')], max_length=20, null=True, verbose_name='Estado Nuevo')),
                ('descripcion_cambio', models.TextField(blank=True, help_text='Descripción detallada del cambio realizado', null=True, verbose_name='Descripción del Cambio')),
                ('campos_modificados', models.JSONField(blank=True, default=dict, help_text='Diccionario JSON con los campos modificados y sus valores anteriores y nuevos', verbose_name='Campos Modificados')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_responsable_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Anterior')),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_responsable_nuevo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Nuevo')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_historial', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Historial de Nota',
                'verbose_name_plural': 'Historial de Notas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre original del archivo', max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_almacenamiento', models.CharField(help_text='Ruta donde se almacena el archivo en el servidor', max_length=500, verbose_name='Ruta de Almacenamiento')),
                ('tipo_mime', models.CharField(help_text='Tipo MIME del archivo (ej: application/pdf, image/jpeg)', max_length=100, verbose_name='Tipo MIME')),
                ('tamaño_bytes', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en Bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('subido_por', models.ForeignKey(help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['estado'], name='notas_nota_estado_13e2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['responsable'], name='notas_nota_respons_4fb56b_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['fecha_ingreso'], name='notas_nota_fecha_i_addce8_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['numero_nota'], name='notas_nota_numero__18c2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='historialnota',
            index=models.Index(fields=['nota', '-fecha_hora'], name='notas_histo_nota_id_41a65b_idx'),
        ),
        migrations.AddIndex(
            model_name='historialnota',
            index=models.Index(fields=['usuario'], name='notas_histo_usuario_3b6804_idx'),
        ),
        migrations.AddIndex(
            model_name='adjunto',
            index=models.Index(fields=['nota'], name='notas_adjun_nota_id_e52654_idx'),
        ),
    ]
