# Generated by Django 6.0.2 on 2026-04-06 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero', models.IntegerField(help_text='Identificador institucional del sector', unique=True, verbose_name='Número')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(blank=True, help_text='Número completo de la nota: {sector.numero}-{numero}-{año} o {sector.numero}-I{secuencia}-{año}', max_length=30, unique=True, verbose_name='Número de Nota')),
                ('tiene_numero_formal', models.BooleanField(default=False, help_text='True si el número lo trajo la nota física (formato completo desde formulario)', verbose_name='Tiene Número Formal')),
                ('fecha_ingreso', models.DateTimeField(help_text='Fecha y hora en que la nota ingresó al sistema', verbose_name='Fecha de Ingreso')),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite para resolver la nota', null=True, verbose_name='Fecha Límite')),
                ('remitente', models.CharField(help_text='Persona o entidad que envía la nota', max_length=200, verbose_name='Remitente')),
                ('emisor_externo', models.CharField(blank=True, help_text='Entidad externa que emite la nota', max_length=200, null=True, verbose_name='Emisor externo')),
                ('area_origen', models.CharField(help_text='Área o departamento de origen de la nota', max_length=100, verbose_name='Área de Origen')),
                ('tema', models.CharField(help_text='Tema o asunto principal de la nota (máximo 100 caracteres)', max_length=100, verbose_name='Tema')),
                ('tarea_asignada', models.CharField(blank=True, help_text='Acción concreta que debe ejecutar el responsable', max_length=200, verbose_name='Tarea Asignada')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del contenido de la nota', verbose_name='Descripción')),
                ('email_respuesta', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de respuesta')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('INGRESADA', 'Ingresada'), ('EN_REVISION', 'En Revisión'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('EN_ESPERA', 'En Espera'), ('DEVUELTA', 'Devuelta'), ('RESUELTA', 'Resuelta'), ('ARCHIVADA', 'Archivada'), ('ANULADA', 'Anulada')], default='INGRESADA', max_length=20, verbose_name='Estado')),
                ('canal_ingreso', models.CharField(choices=[('EMAIL', 'Email'), ('PRESENCIAL', 'Presencial'), ('TELEFONO', 'Teléfono'), ('SISTEMA', 'Sistema'), ('OTRO', 'Otro')], default='PRESENCIAL', max_length=20, verbose_name='Canal de Ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('anulada', models.BooleanField(default=False, help_text='Indica si la nota ha sido anulada', verbose_name='Anulada')),
                ('motivo_anulacion', models.TextField(blank=True, help_text='Motivo por el cual la nota fue anulada', null=True, verbose_name='Motivo de Anulación')),
                ('genera_resolucion', models.BooleanField(default=False, help_text='Indica si esta nota genera una resolución formal', verbose_name='Genera Resolución')),
                ('numero_resolucion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Resolución')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó la nota en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario responsable de procesar la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LegajoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('ruta_servidor', models.CharField(help_text='Ruta donde se almacena en el servidor de RRHH', max_length=500, verbose_name='Ruta en servidor')),
                ('tipo_documento', models.CharField(choices=[('NOTA_ESCANEADA', 'Nota Escaneada'), ('RESOLUCION', 'Resolución'), ('ADJUNTO', 'Adjunto'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_legajo', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_legajo_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_legajo', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Documento de Legajo',
                'verbose_name_plural': 'Documentos de Legajo',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='NotaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_agente_set', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_agente_set', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Nota-Agente',
                'verbose_name_plural': 'Notas-Agentes',
                'unique_together': {('nota', 'agente')},
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='agentes',
            field=models.ManyToManyField(blank=True, help_text='Agentes (personas institucionales) asociados a esta nota', related_name='notas', through='notas.NotaAgente', to=settings.AUTH_USER_MODEL, verbose_name='Agentes'),
        ),
        migrations.AddField(
            model_name='nota',
            name='sector_origen',
            field=models.ForeignKey(blank=True, help_text='Sector interno de origen de la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_origen', to='notas.sector', verbose_name='Sector de Origen'),
        ),
        migrations.CreateModel(
            name='DistribucionResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('medio', models.CharField(choices=[('EMAIL', 'Email'), ('PAPEL', 'Papel'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='Medio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_resolucion', to='notas.nota', verbose_name='Nota')),
                ('sector_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_recibidas', to='notas.sector', verbose_name='Sector destino')),
            ],
            options={
                'verbose_name': 'Distribución de Resolución',
                'verbose_name_plural': 'Distribuciones de Resolución',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el evento', verbose_name='Fecha y Hora')),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('ACTUALIZACION', 'Actualización'), ('ANULACION', 'Anulación'), ('ARCHIVADO', 'Archivado'), ('DERIVACION_DESPACHO', 'Derivación a Despacho'), ('RESOLUCION_CARGADA', 'Resolución Cargada'), ('DISTRIBUCION_SECTOR', 'Distribución a Sector')], max_length=25, verbose_name='Tipo de Evento')),
                ('estado_anterior', models.CharField(blank=True, choices=[('INGRESADA', 'Ingresada'), ('EN_REVISION', 'En Revisión'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('EN_ESPERA', 'En Espera'), ('DEVUELTA', 'Devuelta'), ('RESUELTA', 'Resuelta'), ('ARCHIVADA', 'Archivada'), ('ANULADA', 'Anulada')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, choices=[('INGRESADA', 'Ingresada'), ('EN_REVISION', 'En Revisión'), ('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('EN_ESPERA', 'En Espera'), ('DEVUELTA', 'Devuelta'), ('RESUELTA', 'Resuelta'), ('ARCHIVADA', 'Archivada'), ('ANULADA', 'Anulada')], max_length=20, null=True, verbose_name='Estado Nuevo')),
                ('descripcion_cambio', models.TextField(blank=True, help_text='Descripción detallada del cambio realizado', null=True, verbose_name='Descripción del Cambio')),
                ('campos_modificados', models.JSONField(blank=True, default=dict, help_text='Diccionario JSON con los campos modificados y sus valores anteriores y nuevos', verbose_name='Campos Modificados')),
                ('responsable_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_responsable_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Anterior')),
                ('responsable_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_responsable_nuevo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Nuevo')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_historial', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Historial de Nota',
                'verbose_name_plural': 'Historial de Notas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['nota', '-fecha_hora'], name='notas_histo_nota_id_41a65b_idx'), models.Index(fields=['usuario'], name='notas_histo_usuario_3b6804_idx')],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre original del archivo', max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_almacenamiento', models.CharField(help_text='Ruta donde se almacena el archivo en el servidor', max_length=500, verbose_name='Ruta de Almacenamiento')),
                ('tipo_mime', models.CharField(help_text='Tipo MIME del archivo (ej: application/pdf, image/jpeg)', max_length=100, verbose_name='Tipo MIME')),
                ('tamaño_bytes', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño en Bytes')),
                ('tipo_adjunto', models.CharField(choices=[('DOCUMENTO_ORIGINAL', 'Documento Original'), ('BORRADOR_RESOLUCION', 'Borrador Resolución'), ('RESOLUCION_FINAL', 'Resolución Final'), ('NOTA_ESCANEADA', 'Nota Escaneada'), ('OTRO', 'Otro')], default='OTRO', max_length=25, verbose_name='Tipo de Adjunto')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('subido_por', models.ForeignKey(help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='notas.nota', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-fecha_subida'],
                'indexes': [models.Index(fields=['nota'], name='notas_adjun_nota_id_e52654_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['estado'], name='notas_nota_estado_13e2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['responsable'], name='notas_nota_respons_4fb56b_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['fecha_ingreso'], name='notas_nota_fecha_i_addce8_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['numero_nota'], name='notas_nota_numero__18c2c3_idx'),
        ),
    ]
