# Generated by Django 6.0.2 on 2026-02-21 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('legajo_numero', models.CharField(max_length=20, unique=True, verbose_name='Número de legajo')),
                ('cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('medio', models.CharField(choices=[('EMAIL', 'Email'), ('PAPEL', 'Papel'), ('SISTEMA', 'Sistema')], max_length=20, verbose_name='Medio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Distribución de Resolución',
                'verbose_name_plural': 'Distribuciones de Resolución',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='LegajoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('ruta_servidor', models.CharField(help_text='Ruta donde se almacena en el servidor de RRHH', max_length=500, verbose_name='Ruta en servidor')),
                ('tipo_documento', models.CharField(choices=[('NOTA_ESCANEADA', 'Nota Escaneada'), ('RESOLUCION', 'Resolución'), ('ADJUNTO', 'Adjunto'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
            ],
            options={
                'verbose_name': 'Documento de Legajo',
                'verbose_name_plural': 'Documentos de Legajo',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='NotaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Nota-Agente',
                'verbose_name_plural': 'Notas-Agentes',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero', models.IntegerField(help_text='Identificador institucional del sector', unique=True, verbose_name='Número')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['numero'],
            },
        ),
        migrations.RemoveIndex(
            model_name='nota',
            name='notas_nota_numero__18c2c3_idx',
        ),
        migrations.AddField(
            model_name='adjunto',
            name='tipo_adjunto',
            field=models.CharField(choices=[('DOCUMENTO_ORIGINAL', 'Documento Original'), ('BORRADOR_RESOLUCION', 'Borrador Resolución'), ('RESOLUCION_FINAL', 'Resolución Final'), ('NOTA_ESCANEADA', 'Nota Escaneada'), ('OTRO', 'Otro')], default='OTRO', max_length=25, verbose_name='Tipo de Adjunto'),
        ),
        migrations.AddField(
            model_name='nota',
            name='emisor_externo',
            field=models.CharField(blank=True, help_text='Entidad externa que emite la nota', max_length=200, null=True, verbose_name='Emisor externo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolución'),
        ),
        migrations.AddField(
            model_name='nota',
            name='genera_resolucion',
            field=models.BooleanField(default=False, help_text='Indica si esta nota genera una resolución formal', verbose_name='Genera Resolución'),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero_nota_externo',
            field=models.CharField(blank=True, help_text='Número asignado por el remitente u otro sistema', max_length=50, null=True, verbose_name='Número de Nota (externo)'),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero_nota_interno',
            field=models.CharField(blank=True, help_text='Generado: {sector.numero}-{secuencia}-{año} o INT-{secuencia}-{año}', max_length=30, unique=True, verbose_name='Número de Nota (interno)'),
        ),
        migrations.AddField(
            model_name='nota',
            name='numero_resolucion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Resolución'),
        ),
        migrations.AlterField(
            model_name='historialnota',
            name='tipo_evento',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('ACTUALIZACION', 'Actualización'), ('ANULACION', 'Anulación'), ('ARCHIVADO', 'Archivado'), ('DERIVACION_DESPACHO', 'Derivación a Despacho'), ('RESOLUCION_CARGADA', 'Resolución Cargada'), ('DISTRIBUCION_SECTOR', 'Distribución a Sector')], max_length=25, verbose_name='Tipo de Evento'),
        ),
        migrations.AddField(
            model_name='agente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado (si tiene acceso)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='distribucionresolucion',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribuciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='distribucionresolucion',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_resolucion', to='notas.nota', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='legajodocumento',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_legajo', to='notas.agente', verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='legajodocumento',
            name='cargado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_legajo_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por'),
        ),
        migrations.AddField(
            model_name='legajodocumento',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_legajo', to='notas.nota', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='notaagente',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_agente_set', to='notas.agente', verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='notaagente',
            name='nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_agente_set', to='notas.nota', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='nota',
            name='agentes',
            field=models.ManyToManyField(blank=True, help_text='Agentes asociados a esta nota', related_name='notas', through='notas.NotaAgente', to='notas.agente', verbose_name='Agentes'),
        ),
        migrations.AddField(
            model_name='distribucionresolucion',
            name='sector_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_recibidas', to='notas.sector', verbose_name='Sector destino'),
        ),
        migrations.AddField(
            model_name='agente',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes', to='notas.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='nota',
            name='emisor_sector',
            field=models.ForeignKey(blank=True, help_text='Sector interno que emite la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_emitidas', to='notas.sector', verbose_name='Emisor (sector)'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['numero_nota_interno'], name='notas_nota_numero__5518ab_idx'),
        ),
        migrations.RemoveField(
            model_name='nota',
            name='numero_nota',
        ),
        migrations.AlterUniqueTogether(
            name='notaagente',
            unique_together={('nota', 'agente')},
        ),
    ]
