# Generated by Django 6.0.2 on 2026-02-27 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_agente_distribucionresolucion_legajodocumento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nota',
            name='notas_nota_numero__5518ab_idx',
        ),
        migrations.AddField(
            model_name='nota',
            name='numero_nota',
            field=models.CharField(blank=True, help_text='Número completo de la nota: {sector.numero}-{numero}-{año} o {sector.numero}-I{secuencia}-{año}', max_length=30, unique=True, verbose_name='Número de Nota'),
        ),
        migrations.AddField(
            model_name='nota',
            name='sector_origen',
            field=models.ForeignKey(blank=True, help_text='Sector interno de origen de la nota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_origen', to='notas.sector', verbose_name='Sector de Origen'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tarea_asignada',
            field=models.CharField(blank=True, help_text='Acción concreta que debe ejecutar el responsable', max_length=200, verbose_name='Tarea Asignada'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tiene_numero_formal',
            field=models.BooleanField(default=False, help_text='True si el número lo trajo la nota física (formato completo desde formulario)', verbose_name='Tiene Número Formal'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del contenido de la nota', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='fecha_ingreso',
            field=models.DateTimeField(help_text='Fecha y hora en que la nota ingresó al sistema', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tema',
            field=models.CharField(help_text='Tema o asunto principal de la nota (máximo 100 caracteres)', max_length=100, verbose_name='Tema'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['numero_nota'], name='notas_nota_numero__18c2c3_idx'),
        ),
        migrations.RemoveField(
            model_name='nota',
            name='emisor_sector',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='numero_nota_externo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='numero_nota_interno',
        ),
    ]
