# Generated by Django 6.0.2 on 2026-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_add_sector_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='email_respuesta',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de respuesta'),
        ),
    ]
