# Generated by Django 6.0.2 on 2026-04-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_add_nota_email_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (legajo virtual / RRHH)', max_length=15, null=True, verbose_name='DNI'),
        ),
    ]
