# Generated by Django 6.0.2 on 2026-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido', 'nombres'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad', max_length=15, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(default='Sin nombre', help_text='Número de legajo del usuario (usado para login)', max_length=20, unique=True, verbose_name='Legajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='Sin nombre', max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('OPERADOR', 'Operador'), ('CONSULTOR', 'Consultor')], default='OPERADOR', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
    ]
